DROP DATABASE IF EXISTS QUANLYVIDIENTU;

CREATE DATABASE QUANLYVIDIENTU;

USE QUANLYVIDIENTU;

CREATE TABLE ACCOUNT (
    USER_ID INT NOT NULL AUTO_INCREMENT,
	PHONE_NUMBER VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FULL_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(10),
    PASSWORD VARCHAR(10),
    IS_NEW_USER BIT DEFAULT 0,
    IS_VALIDATED BIT DEFAULT 1,
    FAIL_LOGIN_COUNT INT DEFAULT 0,
    ABNORMAL_LOGIN_COUNT INT DEFAULT 0,
    IS_LOCKED BIT DEFAULT 1,
    KEY (USER_ID)
);